// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbq9DIR2DOeiWyKVUM0WH3W4DA1bvV3dk',
    appId: '1:194557878232:web:5c473aacd72eaf07f91cad',
    messagingSenderId: '194557878232',
    projectId: 'flutter-f3642',
    authDomain: 'flutter-f3642.firebaseapp.com',
    storageBucket: 'flutter-f3642.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBieGowxYmSYmCPLG1cDWh75eIP2Xf3eAk',
    appId: '1:194557878232:android:ecab7b7dfd6d2804f91cad',
    messagingSenderId: '194557878232',
    projectId: 'flutter-f3642',
    storageBucket: 'flutter-f3642.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqag2BrLmm2G32y3ve0iAxpjBgGlJ4CIQ',
    appId: '1:194557878232:ios:c9eb777b82aae49ff91cad',
    messagingSenderId: '194557878232',
    projectId: 'flutter-f3642',
    storageBucket: 'flutter-f3642.appspot.com',
    iosClientId: '194557878232-ptbnsmbr8g1bp40570epfpj0jkl8joaq.apps.googleusercontent.com',
    iosBundleId: 'com.example.stageFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqag2BrLmm2G32y3ve0iAxpjBgGlJ4CIQ',
    appId: '1:194557878232:ios:d23700e472b7e124f91cad',
    messagingSenderId: '194557878232',
    projectId: 'flutter-f3642',
    storageBucket: 'flutter-f3642.appspot.com',
    iosClientId: '194557878232-nfr9g4fg045dka3d32kms1tf008latpj.apps.googleusercontent.com',
    iosBundleId: 'com.example.stageFlutter.RunnerTests',
  );
}
